on: [push]
name: Verify ESlint

jobs:
  test:
    name: run eslint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: MakeTest
      run: |
        npm install
        eslint .
